### ISSUE TITLE
feat: design home page

### ISSUE THREAD

**Issue by paiakarit** [cybermm/cybermm.tech#2]
## ပင်မစာမျက်နှာတွင်ပါ၀င်မည့် အချက်အလက်များ
- header section
- team section
- footer section

## ရှင်းလင်းချက်များ
- header section တွင် အဖွဲ့အစည်း၏ ရည်ရွယ်ချက်နှင့် အစီအစဥ်များအား မိတ်ဆက်ရမည်။
- team section တွင် အဖွဲ့၀င်များအား မိတ်ဆက်ရမည်။
- footer section တွင် ဆက်သွယ်ရန် အချက်အလက်များအား မိတ်ဆက်ရမည်။

## လုပ်ဆောင်ရမည့် လုပ်ငန်းစဥ်အဆင့်ဆင့်များ
- [ ] design system ရေးဆွဲရန်
- [ ] section များအားရေးဆွဲရန်

**Comment by satnaing** [comment]
I'm not good at UI/UX. Though I can help you with frontend if you're using ReactJS.

**Comment by paiakarit** [comment]
A temporary suspension is necessary because there are still no qualified team members and relevant experts to design.
